# Generated by Django 4.0.5 on 2022-08-06 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True, verbose_name='title')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('middle_names', models.CharField(blank=True, default='', max_length=100, verbose_name='middle names')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'health care provider',
                'verbose_name_plural': 'health care providers',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True, verbose_name='title')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('middle_names', models.CharField(blank=True, default='', max_length=100, verbose_name='middle names')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('professional_number', models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='professional number')),
                ('staff_role', models.CharField(choices=[('DR', 'Doctor'), ('NR', 'Nurse'), ('MG', 'Manger'), ('PC', 'Practitioner'), ('AD', 'Admin')], max_length=2, verbose_name='user role')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'staff',
            },
        ),
        migrations.CreateModel(
            name='TelephoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_number', models.CharField(max_length=100, verbose_name='telephone number')),
                ('owner_patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_nums', to='users.patient')),
                ('owner_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_nums', to='users.provider')),
                ('owner_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_nums', to='users.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('date_registration_end', models.DateField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.provider')),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='patients',
            field=models.ManyToManyField(through='users.Registration', to='users.patient'),
        ),
        migrations.AddField(
            model_name='provider',
            name='staff',
            field=models.ManyToManyField(to='users.staff'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(blank=True, default='', max_length=10, verbose_name='unit number')),
                ('first_line', models.CharField(blank=True, default='', max_length=200, verbose_name='fisrt line')),
                ('second_line', models.CharField(blank=True, default='', max_length=200, verbose_name='second line')),
                ('city', models.CharField(blank=True, default='', max_length=200, verbose_name='city')),
                ('governorate', models.CharField(blank=True, default='', max_length=200, verbose_name='governorate')),
                ('patient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.provider')),
                ('staff', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.staff')),
            ],
        ),
    ]
