# Generated by Django 4.0.5 on 2022-07-28 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_birth', models.CharField(max_length=100, verbose_name='date of birth')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.myuser',),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='first name')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('patient', models.ManyToManyField(to='users.patient')),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='professional_number',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_type',
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('professional_number', models.CharField(max_length=100, null=True, unique=True, verbose_name='professional number')),
                ('staff_role', models.CharField(choices=[('DR', 'doctor'), ('NR', 'nurse'), ('MG', 'manger'), ('PC', 'practitioner'), ('AD', 'admin')], max_length=2, verbose_name='user type')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.myuser',),
        ),
        migrations.CreateModel(
            name='TelephoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_number', models.CharField(max_length=100, unique=True, verbose_name='telephone number')),
                ('MyUser_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('provider_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=400, verbose_name='address')),
                ('MyUser_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('provider_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.provider')),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='staff',
            field=models.ManyToManyField(to='users.staff'),
        ),
    ]
