# Generated by Django 4.0.5 on 2022-07-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patient_provider_remove_myuser_professional_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='null', max_length=200, verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='first_line',
            field=models.CharField(default='null', max_length=200, verbose_name='fisrt line'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='governrate',
            field=models.CharField(default='null', max_length=200, verbose_name='governrate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='second_line',
            field=models.CharField(max_length=200, null=True, verbose_name='second line'),
        ),
        migrations.AddField(
            model_name='address',
            name='unit_number',
            field=models.CharField(default='null', max_length=10, verbose_name='unit number'),
            preserve_default=False,
        ),
    ]
