# Generated by Django 4.0.5 on 2022-08-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_registration_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date_registration_end',
            field=models.DateTimeField(null=True),
        ),
    ]
