# Generated by Django 4.0.6 on 2022-07-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_telephonenumber_telephone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='address',
            name='first_line',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='fisrt line'),
        ),
        migrations.AlterField(
            model_name='address',
            name='governorate',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='governorate'),
        ),
        migrations.AlterField(
            model_name='address',
            name='unit_number',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='unit number'),
        ),
    ]
