# Generated by Django 4.0.5 on 2022-08-13 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_registration_date_registered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_employed', models.DateField(auto_now_add=True)),
                ('date_employment_end', models.DateField(null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.provider')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.staff')),
            ],
        ),
    ]
