# Generated by Django 4.0.5 on 2022-08-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_provider_owner_alter_account_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telephonenumber',
            old_name='patient',
            new_name='owner_patient',
        ),
        migrations.RenameField(
            model_name='telephonenumber',
            old_name='provider',
            new_name='owner_provider',
        ),
        migrations.RenameField(
            model_name='telephonenumber',
            old_name='staff',
            new_name='owner_staff',
        ),
        migrations.AlterField(
            model_name='staff',
            name='middle_names',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='middle names'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='title',
            field=models.CharField(max_length=20, null=True, verbose_name='title'),
        ),
    ]
