# Generated by Django 4.0.5 on 2022-08-04 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_patient_telephonenumber_owner_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('date_registration_end', models.DateField(null=True)),
                ('patinet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.patient')),
            ],
        ),
        migrations.RemoveField(
            model_name='provider',
            name='patient',
        ),
        migrations.AddField(
            model_name='provider',
            name='patients',
            field=models.ManyToManyField(through='users.Registration', to='users.patient'),
        ),
        migrations.AlterField(
            model_name='telephonenumber',
            name='owner_patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_nums', to='users.patient'),
        ),
        migrations.AlterField(
            model_name='telephonenumber',
            name='owner_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_nums', to='users.staff'),
        ),
        migrations.AddField(
            model_name='registration',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.provider'),
        ),
    ]
