# Generated by Django 4.0.5 on 2022-08-05 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_registration_remove_provider_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephonenumber',
            name='owner_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_nums', to='users.provider'),
        ),
    ]
