# Generated by Django 4.0.5 on 2022-08-05 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_telephonenumber_owner_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='address',
            name='staff',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.staff'),
        ),
    ]
