# Generated by Django 4.0.5 on 2022-08-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_employment_is_active_alter_staff_account'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employment',
            constraint=models.UniqueConstraint(fields=('provider', 'staff'), name='unique_employment'),
        ),
    ]
