# Generated by Django 4.0.5 on 2022-09-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_employment_unique_employment_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registration',
            name='unique_registration',
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('provider', 'patient'), name='unique_registration'),
        ),
    ]
