# Generated by Django 4.0.6 on 2022-09-10 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_patient_gender'),
        ('records', '0003_viewedrecordevenet'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordUpdateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_of_update', models.DateTimeField(auto_now_add=True)),
                ('prev_history', models.TextField(blank=True, null=True)),
                ('prev_examination', models.TextField(blank=True, null=True)),
                ('prev_diagnosis', models.TextField(blank=True, null=True)),
                ('prev_managment_plan', models.TextField(blank=True, null=True)),
                ('prev_is_public', models.BooleanField(blank=True)),
                ('new_history', models.TextField(blank=True, null=True)),
                ('new_examination', models.TextField(blank=True, null=True)),
                ('new_diagnosis', models.TextField(blank=True, null=True)),
                ('new_managment_plan', models.TextField(blank=True, null=True)),
                ('new_is_public', models.BooleanField(blank=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='records.record')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.staff')),
            ],
        ),
    ]
