# Generated by Django 4.0.6 on 2022-09-19 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_rename_viewedrecordevenet_viewedrecordevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastconditions',
            name='date_diagnosed',
            field=models.DateField(blank=True, default=datetime.date(2022, 9, 19)),
        ),
    ]
