# Generated by Django 4.0.5 on 2022-10-01 10:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import records.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_patient_gender'),
        ('records', '0008_alter_pastconditions_date_diagnosed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastconditions',
            name='date_diagnosed',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 1)),
        ),
        migrations.CreateModel(
            name='RecordFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=records.models.upload_to, verbose_name='file')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.record')),
                ('uploaded_by_patient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.patient')),
                ('uploaded_by_staff', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.staff')),
            ],
        ),
    ]
