# Generated by Django 4.0.6 on 2022-10-05 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_pastconditions_date_diagnosed_recordfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordfile',
            name='file_name',
            field=models.CharField(default='fefe', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pastconditions',
            name='date_diagnosed',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 5)),
        ),
    ]
