# Generated by Django 4.0.6 on 2022-10-11 10:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_patient_gender'),
        ('records', '0011_alter_recordfile_uploaded_by_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordfile',
            name='record',
        ),
        migrations.RemoveField(
            model_name='recordfile',
            name='uploaded_by_patient',
        ),
        migrations.AddField(
            model_name='recordfile',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pastconditions',
            name='date_diagnosed',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 11)),
        ),
    ]
