# Generated by Django 4.0.6 on 2022-10-11 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0015_patient_gender'),
        ('records', '0013_alter_recordfile_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordfile',
            name='uploaded_by_staff',
        ),
        migrations.AddField(
            model_name='recordfile',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recordfile',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
    ]
