# Generated by Django 4.0.6 on 2022-10-12 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_remove_recordfile_uploaded_by_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienticdcode',
            name='title',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pastconditions',
            name='date_diagnosed',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 12)),
        ),
    ]
