FROM node:18-alpine AS build-stage
WORKDIR /app  
COPY package*.json /app/
ENV NODE_OPTIONS="--max-old-space-size=2048"
RUN npm install 
COPY . /app/
RUN sudo npm run build

FROM nginx:1.12-alpine AS production-stage
# RUN addgroup app && adduser -S -G app app
# USER app
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 80


ENTRYPOINT ["nginx", "-g", "daemon off;" ]