version: "2.1"

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes: 
      - frontend_volume:/app/build
    ports:
      - 3000:80
    
    restart: unless-stopped


  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn oneSystem_core.wsgi:application --bind 0.0.0.0:8000
    
    volumes:
      - static_volume:/home/app/backend/staticfiles
      - media_volume:/home/app/backend/media
    expose:
      - 8000
    restart: unless-stopped 
    env_file:
      - ./backend/.env.prod
    depends_on:
      - db


  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env.prod.db


  nginx:
    build: ./nginx
    volumes:
      - frontend_volume:/usr/share/nginx/html
      - static_volume:/home/app/backend/staticfiles
      - media_volume:/home/app/backend/media
    ports:
      - 1337:80
    depends_on:
      - backend
      - frontend


volumes:
  postgres_data:
  static_volume:
  media_volume:
  frontend_volume:
    
 