FROM python:3.9.6-alpine

# set work directory
WORKDIR /usr/src/backend

ENV DEBUG  "True"
ENV FRONT_ENDPOINT "127.0.0.1"
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .

EXPOSE 8000
CMD ["python","manage.py", "runserver", "0.0.0.0:8000"]
