# Generated by Django 4.0.5 on 2022-11-15 17:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_session_end_remove_session_start_session_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start_time',
        ),
        migrations.AddField(
            model_name='session',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 17, 54, 52, 880942, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 17, 54, 59, 825003, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
