# Generated by Django 4.0.5 on 2022-12-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_session_date_remove_session_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('BD', 'Booked'), ('AV', 'Availble'), ('BLC', 'BLOCKED')], default='AV', max_length=3, verbose_name='status'),
        ),
    ]
