# Generated by Django 4.0.6 on 2022-11-14 18:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_patient_gender'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='end',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start',
        ),
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.date(2022, 11, 14)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 14, 18, 48, 49, 882704, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 14, 18, 48, 54, 819208, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SessionPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.provider')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.session')),
            ],
        ),
    ]
