# Generated by Django 4.0.6 on 2022-09-18 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_patient_gender'),
        ('records', '0005_alter_note_author_alter_note_patient_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ViewedRecordEvenet',
            new_name='ViewedRecordEvent',
        ),
        migrations.CreateModel(
            name='PatientIcdCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('code', models.CharField(max_length=20)),
                ('selectedText', models.CharField(max_length=200)),
                ('linearizationUri', models.CharField(max_length=200)),
                ('foundationUri', models.CharField(max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.staff')),
            ],
        ),
        migrations.CreateModel(
            name='PastConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diagnosed', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(max_length=600)),
                ('icd_code', models.CharField(blank=True, max_length=20, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.staff')),
            ],
        ),
    ]
