# Generated by Django 4.0.5 on 2022-08-14 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginToProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.provider')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.staff')),
            ],
        ),
    ]
