# Generated by Django 4.0.5 on 2022-08-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_logintoprovider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginToProvider',
            new_name='LoginToProviderEvent',
        ),
    ]
