# Generated by Django 4.0.5 on 2022-08-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_employment_unique_employment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employment',
            name='unique_employment',
        ),
        migrations.AddConstraint(
            model_name='employment',
            constraint=models.UniqueConstraint(fields=('provider', 'staff', 'is_active'), name='unique_employment'),
        ),
    ]
