# Generated by Django 4.0.5 on 2022-12-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_employment_employment_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='employment_role',
            field=models.CharField(choices=[('DR', 'Doctor'), ('NR', 'Nurse'), ('MG', 'Manger'), ('PC', 'Practitioner'), ('AD', 'Admin')], default='MG', max_length=2, verbose_name='user role'),
            preserve_default=False,
        ),
    ]
