# Generated by Django 4.0.5 on 2022-12-19 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_employment_employment_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTelephoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_number', models.CharField(max_length=100, verbose_name='telephone number')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.staff')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderTelephoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_number', models.CharField(max_length=100, verbose_name='telephone number')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.provider')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTelephoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_number', models.CharField(max_length=100, verbose_name='telephone number')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(blank=True, default='', max_length=10, verbose_name='unit number')),
                ('first_line', models.CharField(blank=True, default='', max_length=200, verbose_name='fisrt line')),
                ('second_line', models.CharField(blank=True, default='', max_length=200, verbose_name='second line')),
                ('city', models.CharField(blank=True, default='', max_length=200, verbose_name='city')),
                ('governorate', models.CharField(blank=True, default='', max_length=200, verbose_name='governorate')),
                ('patient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='BranchTelephoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_number', models.CharField(max_length=100, verbose_name='telephone number')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch')),
            ],
        ),
        migrations.CreateModel(
            name='BranchAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(blank=True, default='', max_length=10, verbose_name='unit number')),
                ('first_line', models.CharField(blank=True, default='', max_length=200, verbose_name='fisrt line')),
                ('second_line', models.CharField(blank=True, default='', max_length=200, verbose_name='second line')),
                ('city', models.CharField(blank=True, default='', max_length=200, verbose_name='city')),
                ('governorate', models.CharField(blank=True, default='', max_length=200, verbose_name='governorate')),
                ('branch', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch')),
            ],
        ),
    ]
