# Generated by Django 4.0.6 on 2023-03-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_rename_branch_branchtelephonenumbers_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employment',
            name='employment_role',
            field=models.CharField(choices=[('DR', 'Doctor'), ('NR', 'Nurse'), ('MG', 'Manger'), ('PC', 'Practitioner'), ('AD', 'Admin'), ('OW', 'Owner')], max_length=2, verbose_name='user role'),
        ),
    ]
