# Generated by Django 4.0.6 on 2023-04-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_account_is_staff_alter_employment_employment_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employment',
            name='employment_role',
            field=models.CharField(choices=[('DR', 'Doctor'), ('NR', 'Nurse'), ('MG', 'Manger'), ('PC', 'Practitioner'), ('AD', 'Admin'), ('OW', 'Owner')], max_length=6, verbose_name='user role'),
        ),
    ]
